// examples/vue-app/src/App.vue
<template>
  <router-view />
</template>

<script>
import { Userpilot } from "userpilot";

export default {
  name: "App",
  created() {
    if (localStorage.getItem("authenticated") === "true") {
      console.groupCollapsed('[Userpilot] Identify')
      console.info("call `Userpilot.identify()`");
      console.log("Replace {4321984} with the logged in user identifier");
      console.groupEnd();
      Userpilot.identify("4321984", {
        name: "John Doe",
        email: "john@site-domain.com",
        created_at: "2018-07-11",
      });
      
      console.groupCollapsed('[Userpilot] Reload')
      console.log("Call Userpilot.reload() after identify");
      console.groupEnd();
      Userpilot.reload();
    }
  },
  watch: {
    $route() {
      const authenticated = localStorage.getItem("authenticated");
      if (authenticated === "true") {
        console.groupCollapsed('[Userpilot] Reload')
        console.log("Call Userpilot.reload() on page changes");
        console.log(
          "If you want to trigger experiences on anonymous users, no need to check if the user is authenticated."
        );
        console.groupEnd();
        Userpilot.reload();
      }
    },
  },
};
</script>

<style src="./styles/app.scss" lang="scss"/>

// examples/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { AuthService } from './pages/auth/services';
import { Observable } from 'rxjs';
import {User} from './pages/auth/models';
import {Userpilot} from 'userpilot';




// Initialize Userpilot
console.info('[Userpilot] Initialize');
console.warn('[Userpilot] Replace {AppToken} with your AppToken');
Userpilot.initialize('{AppToken}');



@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor(
    private userService: AuthService
  ) {
    const token = localStorage.getItem('token');
    if(token){
      console.info('[Userpilot] Userpilot.identify()');
      console.warn('[Userpilot] Replace {userId} with the logged in user identifier');
      this.userService.getUser().subscribe((user) => {
        if(user.id){
          Userpilot.identify(user.id,{
            name: user.name,
            email: 'john@site-domain.com',
            created_at: new Date(),
          });
        }
        
      });
    }
    
  }
}
